/**
 * OM SAI — Bills & Invoices page.
 * Invoices are generated by admin (Admin Dashboard → Invoice
 * Management) once a booking/quotation is completed.
 */
(function () {
  if (!Auth.requireAuth()) return;

  const listEl = document.getElementById("invoice-list");
  const emptyEl = document.getElementById("invoice-empty");

  function renderItems(items) {
    return items
      .map((it) => `<tr><td>${it.description}</td><td>${it.qty}</td><td>${fmtCurrency(it.rate)}</td><td>${fmtCurrency(it.qty * it.rate)}</td></tr>`)
      .join("");
  }

  async function load() {
    try {
      const invoices = await Api.get("/invoices/me");
      if (!invoices.length) {
        emptyEl.style.display = "block";
        listEl.innerHTML = "";
        return;
      }
      emptyEl.style.display = "none";
      listEl.innerHTML = invoices
        .map(
          (inv) => `
        <div class="panel" id="invoice-${inv.id}">
          <div class="panel-head">
            <div>
              <strong>Invoice #OMS-${String(inv.id).padStart(4, "0")}</strong>
              <div class="eyebrow" style="margin-top:6px">Issued ${fmtDate(inv.created_at)}</div>
            </div>
            <span class="badge badge-${inv.status}">${inv.status}</span>
          </div>
          <div class="table-wrap" style="margin:16px 0">
            <table class="data-table">
              <thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead>
              <tbody>${renderItems(inv.items)}</tbody>
              <tfoot>
                <tr><td colspan="3" style="text-align:right;font-weight:600">Total</td><td style="font-weight:700">${fmtCurrency(inv.total)}</td></tr>
              </tfoot>
            </table>
          </div>
          <div class="spec-actions">
            <button class="btn btn-outline btn-sm" onclick="window.print()">Download / Print</button>
            ${inv.status !== "paid" ? `<a class="btn btn-primary btn-sm" href="payments.html?invoice=${inv.id}">Pay this invoice</a>` : ""}
          </div>
        </div>`
        )
        .join("");
    } catch (err) {
      toast(err.message, "error");
    }
  }
  load();
})();
